# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/howle/prog/Cpp/WTexn/C/Project_2.0/comand_4.12/command

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/howle/prog/Cpp/WTexn/C/Project_2.0/comand_4.12/command

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.12.4/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/howle/prog/Cpp/WTexn/C/Project_2.0/comand_4.12/command/CMakeFiles /Users/howle/prog/Cpp/WTexn/C/Project_2.0/comand_4.12/command/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/howle/prog/Cpp/WTexn/C/Project_2.0/comand_4.12/command/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named command

# Build rule for target.
command: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 command
.PHONY : command

# fast build rule for target.
command/fast:
	$(MAKE) -f CMakeFiles/command.dir/build.make CMakeFiles/command.dir/build
.PHONY : command/fast

#=============================================================================
# Target rules for targets named Recovery_Arch

# Build rule for target.
Recovery_Arch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Recovery_Arch
.PHONY : Recovery_Arch

# fast build rule for target.
Recovery_Arch/fast:
	$(MAKE) -f CMakeFiles/Recovery_Arch.dir/build.make CMakeFiles/Recovery_Arch.dir/build
.PHONY : Recovery_Arch/fast

#=============================================================================
# Target rules for targets named Test_Interface

# Build rule for target.
Test_Interface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Test_Interface
.PHONY : Test_Interface

# fast build rule for target.
Test_Interface/fast:
	$(MAKE) -f CMakeFiles/Test_Interface.dir/build.make CMakeFiles/Test_Interface.dir/build
.PHONY : Test_Interface/fast

#=============================================================================
# Target rules for targets named Read_Arch

# Build rule for target.
Read_Arch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Read_Arch
.PHONY : Read_Arch

# fast build rule for target.
Read_Arch/fast:
	$(MAKE) -f CMakeFiles/Read_Arch.dir/build.make CMakeFiles/Read_Arch.dir/build
.PHONY : Read_Arch/fast

#=============================================================================
# Target rules for targets named Write_Liner

# Build rule for target.
Write_Liner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Write_Liner
.PHONY : Write_Liner

# fast build rule for target.
Write_Liner/fast:
	$(MAKE) -f CMakeFiles/Write_Liner.dir/build.make CMakeFiles/Write_Liner.dir/build
.PHONY : Write_Liner/fast

#=============================================================================
# Target rules for targets named FileInfo

# Build rule for target.
FileInfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FileInfo
.PHONY : FileInfo

# fast build rule for target.
FileInfo/fast:
	$(MAKE) -f CMakeFiles/FileInfo.dir/build.make CMakeFiles/FileInfo.dir/build
.PHONY : FileInfo/fast

FileInfo.o: FileInfo.cpp.o

.PHONY : FileInfo.o

# target to build an object file
FileInfo.cpp.o:
	$(MAKE) -f CMakeFiles/command.dir/build.make CMakeFiles/command.dir/FileInfo.cpp.o
	$(MAKE) -f CMakeFiles/Recovery_Arch.dir/build.make CMakeFiles/Recovery_Arch.dir/FileInfo.cpp.o
	$(MAKE) -f CMakeFiles/Test_Interface.dir/build.make CMakeFiles/Test_Interface.dir/FileInfo.cpp.o
	$(MAKE) -f CMakeFiles/Read_Arch.dir/build.make CMakeFiles/Read_Arch.dir/FileInfo.cpp.o
	$(MAKE) -f CMakeFiles/Write_Liner.dir/build.make CMakeFiles/Write_Liner.dir/FileInfo.cpp.o
	$(MAKE) -f CMakeFiles/FileInfo.dir/build.make CMakeFiles/FileInfo.dir/FileInfo.cpp.o
.PHONY : FileInfo.cpp.o

FileInfo.i: FileInfo.cpp.i

.PHONY : FileInfo.i

# target to preprocess a source file
FileInfo.cpp.i:
	$(MAKE) -f CMakeFiles/command.dir/build.make CMakeFiles/command.dir/FileInfo.cpp.i
	$(MAKE) -f CMakeFiles/Recovery_Arch.dir/build.make CMakeFiles/Recovery_Arch.dir/FileInfo.cpp.i
	$(MAKE) -f CMakeFiles/Test_Interface.dir/build.make CMakeFiles/Test_Interface.dir/FileInfo.cpp.i
	$(MAKE) -f CMakeFiles/Read_Arch.dir/build.make CMakeFiles/Read_Arch.dir/FileInfo.cpp.i
	$(MAKE) -f CMakeFiles/Write_Liner.dir/build.make CMakeFiles/Write_Liner.dir/FileInfo.cpp.i
	$(MAKE) -f CMakeFiles/FileInfo.dir/build.make CMakeFiles/FileInfo.dir/FileInfo.cpp.i
.PHONY : FileInfo.cpp.i

FileInfo.s: FileInfo.cpp.s

.PHONY : FileInfo.s

# target to generate assembly for a file
FileInfo.cpp.s:
	$(MAKE) -f CMakeFiles/command.dir/build.make CMakeFiles/command.dir/FileInfo.cpp.s
	$(MAKE) -f CMakeFiles/Recovery_Arch.dir/build.make CMakeFiles/Recovery_Arch.dir/FileInfo.cpp.s
	$(MAKE) -f CMakeFiles/Test_Interface.dir/build.make CMakeFiles/Test_Interface.dir/FileInfo.cpp.s
	$(MAKE) -f CMakeFiles/Read_Arch.dir/build.make CMakeFiles/Read_Arch.dir/FileInfo.cpp.s
	$(MAKE) -f CMakeFiles/Write_Liner.dir/build.make CMakeFiles/Write_Liner.dir/FileInfo.cpp.s
	$(MAKE) -f CMakeFiles/FileInfo.dir/build.make CMakeFiles/FileInfo.dir/FileInfo.cpp.s
.PHONY : FileInfo.cpp.s

Read_Arch.o: Read_Arch.cpp.o

.PHONY : Read_Arch.o

# target to build an object file
Read_Arch.cpp.o:
	$(MAKE) -f CMakeFiles/command.dir/build.make CMakeFiles/command.dir/Read_Arch.cpp.o
	$(MAKE) -f CMakeFiles/Recovery_Arch.dir/build.make CMakeFiles/Recovery_Arch.dir/Read_Arch.cpp.o
	$(MAKE) -f CMakeFiles/Test_Interface.dir/build.make CMakeFiles/Test_Interface.dir/Read_Arch.cpp.o
	$(MAKE) -f CMakeFiles/Read_Arch.dir/build.make CMakeFiles/Read_Arch.dir/Read_Arch.cpp.o
	$(MAKE) -f CMakeFiles/Write_Liner.dir/build.make CMakeFiles/Write_Liner.dir/Read_Arch.cpp.o
	$(MAKE) -f CMakeFiles/FileInfo.dir/build.make CMakeFiles/FileInfo.dir/Read_Arch.cpp.o
.PHONY : Read_Arch.cpp.o

Read_Arch.i: Read_Arch.cpp.i

.PHONY : Read_Arch.i

# target to preprocess a source file
Read_Arch.cpp.i:
	$(MAKE) -f CMakeFiles/command.dir/build.make CMakeFiles/command.dir/Read_Arch.cpp.i
	$(MAKE) -f CMakeFiles/Recovery_Arch.dir/build.make CMakeFiles/Recovery_Arch.dir/Read_Arch.cpp.i
	$(MAKE) -f CMakeFiles/Test_Interface.dir/build.make CMakeFiles/Test_Interface.dir/Read_Arch.cpp.i
	$(MAKE) -f CMakeFiles/Read_Arch.dir/build.make CMakeFiles/Read_Arch.dir/Read_Arch.cpp.i
	$(MAKE) -f CMakeFiles/Write_Liner.dir/build.make CMakeFiles/Write_Liner.dir/Read_Arch.cpp.i
	$(MAKE) -f CMakeFiles/FileInfo.dir/build.make CMakeFiles/FileInfo.dir/Read_Arch.cpp.i
.PHONY : Read_Arch.cpp.i

Read_Arch.s: Read_Arch.cpp.s

.PHONY : Read_Arch.s

# target to generate assembly for a file
Read_Arch.cpp.s:
	$(MAKE) -f CMakeFiles/command.dir/build.make CMakeFiles/command.dir/Read_Arch.cpp.s
	$(MAKE) -f CMakeFiles/Recovery_Arch.dir/build.make CMakeFiles/Recovery_Arch.dir/Read_Arch.cpp.s
	$(MAKE) -f CMakeFiles/Test_Interface.dir/build.make CMakeFiles/Test_Interface.dir/Read_Arch.cpp.s
	$(MAKE) -f CMakeFiles/Read_Arch.dir/build.make CMakeFiles/Read_Arch.dir/Read_Arch.cpp.s
	$(MAKE) -f CMakeFiles/Write_Liner.dir/build.make CMakeFiles/Write_Liner.dir/Read_Arch.cpp.s
	$(MAKE) -f CMakeFiles/FileInfo.dir/build.make CMakeFiles/FileInfo.dir/Read_Arch.cpp.s
.PHONY : Read_Arch.cpp.s

Recovery_Arch.o: Recovery_Arch.cpp.o

.PHONY : Recovery_Arch.o

# target to build an object file
Recovery_Arch.cpp.o:
	$(MAKE) -f CMakeFiles/command.dir/build.make CMakeFiles/command.dir/Recovery_Arch.cpp.o
	$(MAKE) -f CMakeFiles/Recovery_Arch.dir/build.make CMakeFiles/Recovery_Arch.dir/Recovery_Arch.cpp.o
	$(MAKE) -f CMakeFiles/Test_Interface.dir/build.make CMakeFiles/Test_Interface.dir/Recovery_Arch.cpp.o
	$(MAKE) -f CMakeFiles/Read_Arch.dir/build.make CMakeFiles/Read_Arch.dir/Recovery_Arch.cpp.o
	$(MAKE) -f CMakeFiles/Write_Liner.dir/build.make CMakeFiles/Write_Liner.dir/Recovery_Arch.cpp.o
	$(MAKE) -f CMakeFiles/FileInfo.dir/build.make CMakeFiles/FileInfo.dir/Recovery_Arch.cpp.o
.PHONY : Recovery_Arch.cpp.o

Recovery_Arch.i: Recovery_Arch.cpp.i

.PHONY : Recovery_Arch.i

# target to preprocess a source file
Recovery_Arch.cpp.i:
	$(MAKE) -f CMakeFiles/command.dir/build.make CMakeFiles/command.dir/Recovery_Arch.cpp.i
	$(MAKE) -f CMakeFiles/Recovery_Arch.dir/build.make CMakeFiles/Recovery_Arch.dir/Recovery_Arch.cpp.i
	$(MAKE) -f CMakeFiles/Test_Interface.dir/build.make CMakeFiles/Test_Interface.dir/Recovery_Arch.cpp.i
	$(MAKE) -f CMakeFiles/Read_Arch.dir/build.make CMakeFiles/Read_Arch.dir/Recovery_Arch.cpp.i
	$(MAKE) -f CMakeFiles/Write_Liner.dir/build.make CMakeFiles/Write_Liner.dir/Recovery_Arch.cpp.i
	$(MAKE) -f CMakeFiles/FileInfo.dir/build.make CMakeFiles/FileInfo.dir/Recovery_Arch.cpp.i
.PHONY : Recovery_Arch.cpp.i

Recovery_Arch.s: Recovery_Arch.cpp.s

.PHONY : Recovery_Arch.s

# target to generate assembly for a file
Recovery_Arch.cpp.s:
	$(MAKE) -f CMakeFiles/command.dir/build.make CMakeFiles/command.dir/Recovery_Arch.cpp.s
	$(MAKE) -f CMakeFiles/Recovery_Arch.dir/build.make CMakeFiles/Recovery_Arch.dir/Recovery_Arch.cpp.s
	$(MAKE) -f CMakeFiles/Test_Interface.dir/build.make CMakeFiles/Test_Interface.dir/Recovery_Arch.cpp.s
	$(MAKE) -f CMakeFiles/Read_Arch.dir/build.make CMakeFiles/Read_Arch.dir/Recovery_Arch.cpp.s
	$(MAKE) -f CMakeFiles/Write_Liner.dir/build.make CMakeFiles/Write_Liner.dir/Recovery_Arch.cpp.s
	$(MAKE) -f CMakeFiles/FileInfo.dir/build.make CMakeFiles/FileInfo.dir/Recovery_Arch.cpp.s
.PHONY : Recovery_Arch.cpp.s

Test_Interface.o: Test_Interface.cpp.o

.PHONY : Test_Interface.o

# target to build an object file
Test_Interface.cpp.o:
	$(MAKE) -f CMakeFiles/command.dir/build.make CMakeFiles/command.dir/Test_Interface.cpp.o
	$(MAKE) -f CMakeFiles/Recovery_Arch.dir/build.make CMakeFiles/Recovery_Arch.dir/Test_Interface.cpp.o
	$(MAKE) -f CMakeFiles/Test_Interface.dir/build.make CMakeFiles/Test_Interface.dir/Test_Interface.cpp.o
	$(MAKE) -f CMakeFiles/Read_Arch.dir/build.make CMakeFiles/Read_Arch.dir/Test_Interface.cpp.o
	$(MAKE) -f CMakeFiles/Write_Liner.dir/build.make CMakeFiles/Write_Liner.dir/Test_Interface.cpp.o
	$(MAKE) -f CMakeFiles/FileInfo.dir/build.make CMakeFiles/FileInfo.dir/Test_Interface.cpp.o
.PHONY : Test_Interface.cpp.o

Test_Interface.i: Test_Interface.cpp.i

.PHONY : Test_Interface.i

# target to preprocess a source file
Test_Interface.cpp.i:
	$(MAKE) -f CMakeFiles/command.dir/build.make CMakeFiles/command.dir/Test_Interface.cpp.i
	$(MAKE) -f CMakeFiles/Recovery_Arch.dir/build.make CMakeFiles/Recovery_Arch.dir/Test_Interface.cpp.i
	$(MAKE) -f CMakeFiles/Test_Interface.dir/build.make CMakeFiles/Test_Interface.dir/Test_Interface.cpp.i
	$(MAKE) -f CMakeFiles/Read_Arch.dir/build.make CMakeFiles/Read_Arch.dir/Test_Interface.cpp.i
	$(MAKE) -f CMakeFiles/Write_Liner.dir/build.make CMakeFiles/Write_Liner.dir/Test_Interface.cpp.i
	$(MAKE) -f CMakeFiles/FileInfo.dir/build.make CMakeFiles/FileInfo.dir/Test_Interface.cpp.i
.PHONY : Test_Interface.cpp.i

Test_Interface.s: Test_Interface.cpp.s

.PHONY : Test_Interface.s

# target to generate assembly for a file
Test_Interface.cpp.s:
	$(MAKE) -f CMakeFiles/command.dir/build.make CMakeFiles/command.dir/Test_Interface.cpp.s
	$(MAKE) -f CMakeFiles/Recovery_Arch.dir/build.make CMakeFiles/Recovery_Arch.dir/Test_Interface.cpp.s
	$(MAKE) -f CMakeFiles/Test_Interface.dir/build.make CMakeFiles/Test_Interface.dir/Test_Interface.cpp.s
	$(MAKE) -f CMakeFiles/Read_Arch.dir/build.make CMakeFiles/Read_Arch.dir/Test_Interface.cpp.s
	$(MAKE) -f CMakeFiles/Write_Liner.dir/build.make CMakeFiles/Write_Liner.dir/Test_Interface.cpp.s
	$(MAKE) -f CMakeFiles/FileInfo.dir/build.make CMakeFiles/FileInfo.dir/Test_Interface.cpp.s
.PHONY : Test_Interface.cpp.s

Write_Liner.o: Write_Liner.cpp.o

.PHONY : Write_Liner.o

# target to build an object file
Write_Liner.cpp.o:
	$(MAKE) -f CMakeFiles/command.dir/build.make CMakeFiles/command.dir/Write_Liner.cpp.o
	$(MAKE) -f CMakeFiles/Recovery_Arch.dir/build.make CMakeFiles/Recovery_Arch.dir/Write_Liner.cpp.o
	$(MAKE) -f CMakeFiles/Test_Interface.dir/build.make CMakeFiles/Test_Interface.dir/Write_Liner.cpp.o
	$(MAKE) -f CMakeFiles/Read_Arch.dir/build.make CMakeFiles/Read_Arch.dir/Write_Liner.cpp.o
	$(MAKE) -f CMakeFiles/Write_Liner.dir/build.make CMakeFiles/Write_Liner.dir/Write_Liner.cpp.o
	$(MAKE) -f CMakeFiles/FileInfo.dir/build.make CMakeFiles/FileInfo.dir/Write_Liner.cpp.o
.PHONY : Write_Liner.cpp.o

Write_Liner.i: Write_Liner.cpp.i

.PHONY : Write_Liner.i

# target to preprocess a source file
Write_Liner.cpp.i:
	$(MAKE) -f CMakeFiles/command.dir/build.make CMakeFiles/command.dir/Write_Liner.cpp.i
	$(MAKE) -f CMakeFiles/Recovery_Arch.dir/build.make CMakeFiles/Recovery_Arch.dir/Write_Liner.cpp.i
	$(MAKE) -f CMakeFiles/Test_Interface.dir/build.make CMakeFiles/Test_Interface.dir/Write_Liner.cpp.i
	$(MAKE) -f CMakeFiles/Read_Arch.dir/build.make CMakeFiles/Read_Arch.dir/Write_Liner.cpp.i
	$(MAKE) -f CMakeFiles/Write_Liner.dir/build.make CMakeFiles/Write_Liner.dir/Write_Liner.cpp.i
	$(MAKE) -f CMakeFiles/FileInfo.dir/build.make CMakeFiles/FileInfo.dir/Write_Liner.cpp.i
.PHONY : Write_Liner.cpp.i

Write_Liner.s: Write_Liner.cpp.s

.PHONY : Write_Liner.s

# target to generate assembly for a file
Write_Liner.cpp.s:
	$(MAKE) -f CMakeFiles/command.dir/build.make CMakeFiles/command.dir/Write_Liner.cpp.s
	$(MAKE) -f CMakeFiles/Recovery_Arch.dir/build.make CMakeFiles/Recovery_Arch.dir/Write_Liner.cpp.s
	$(MAKE) -f CMakeFiles/Test_Interface.dir/build.make CMakeFiles/Test_Interface.dir/Write_Liner.cpp.s
	$(MAKE) -f CMakeFiles/Read_Arch.dir/build.make CMakeFiles/Read_Arch.dir/Write_Liner.cpp.s
	$(MAKE) -f CMakeFiles/Write_Liner.dir/build.make CMakeFiles/Write_Liner.dir/Write_Liner.cpp.s
	$(MAKE) -f CMakeFiles/FileInfo.dir/build.make CMakeFiles/FileInfo.dir/Write_Liner.cpp.s
.PHONY : Write_Liner.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/command.dir/build.make CMakeFiles/command.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/command.dir/build.make CMakeFiles/command.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/command.dir/build.make CMakeFiles/command.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... command"
	@echo "... Recovery_Arch"
	@echo "... Test_Interface"
	@echo "... edit_cache"
	@echo "... Read_Arch"
	@echo "... Write_Liner"
	@echo "... rebuild_cache"
	@echo "... FileInfo"
	@echo "... FileInfo.o"
	@echo "... FileInfo.i"
	@echo "... FileInfo.s"
	@echo "... Read_Arch.o"
	@echo "... Read_Arch.i"
	@echo "... Read_Arch.s"
	@echo "... Recovery_Arch.o"
	@echo "... Recovery_Arch.i"
	@echo "... Recovery_Arch.s"
	@echo "... Test_Interface.o"
	@echo "... Test_Interface.i"
	@echo "... Test_Interface.s"
	@echo "... Write_Liner.o"
	@echo "... Write_Liner.i"
	@echo "... Write_Liner.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

