all:
	#g++ Test_huffman.cpp ../Huffman.cpp -o test
	#g++ Test_Selector.cpp ../Selector.cpp ../LZW.cpp -o test
	g++ Test_Selector.cpp ../Selector.cpp ../Huffman.cpp -o test
	#g++ Test_LZW.cpp ../LZW.cpp -o test