all:
	#g++ Test_Compress.cpp ../Selector.cpp ../LZW.cpp RW_Liner.cpp RW_Interface.cpp FileInfo.cpp -o test
	g++ Test_Compress_And_Decompress.cpp ../Selector.cpp ../LZW.cpp RW_Liner.cpp RW_Interface.cpp FileInfo.cpp -o test